@HOST = http://django:8080/api

###
# @name login
# @prompt username
# @prompt password
POST {{HOST}}/auth/login/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
GET {{HOST}}/weather/data
Authorization: Bearer {{login.response.body.$.access_token}}

###
GET {{HOST}}/geolotes
Authorization: Bearer {{login.response.body.$.access_token}}

###
GET {{HOST}}/areas
Authorization: Bearer {{login.response.body.$.access_token}}

###
GET {{HOST}}/plantas
Authorization: Bearer {{login.response.body.$.access_token}}

###
PUT {{HOST}}/plantas/fotos/upload/
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=elAmor

--elAmor
Content-Type: image/jpg
Content-Disposition: form-data; name="file"; filename="20240412-165539_A1CZ_L1_F1_P6_LA.jpg"

< /home/wceli/Pictures/Screenshots/Screenshot_20240409_124452.png
--elAmor--

