# Generated by Django 4.2.1 on 2024-01-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0039_enfermedad_remove_lectura_cherelles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='Id_Lote',
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Area', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
                ('Variedad', models.CharField(max_length=20, null=True)),
                ('Hectareas', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Usuario', models.TextField(default='Admin', max_length=100, null=True)),
                ('Id_Lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='Id_Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.area'),
        ),
    ]
