# Generated by Django 4.2.1 on 2024-01-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hacienda", "0044_alter_area_id_lote_alter_lote_id_proyecto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poligono",
            name="Id_Area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Poligonos",
                to="Hacienda.area",
            ),
        ),
        migrations.AlterField(
            model_name="poligono",
            name="Id_Lote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Poligonos",
                to="Hacienda.lote",
            ),
        ),
    ]
