# Generated by Django 4.2.1 on 2024-01-19 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hacienda', '0045_alter_poligono_id_area_alter_poligono_id_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='geocoordenadas',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='hacienda',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='poligono',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='area',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocoordenadas',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hacienda',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poligono',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccion',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Id_Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
