# Generated by Django 4.2.1 on 2024-02-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0047_alter_area_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=19, null=True),
        ),
    ]
