# Generated by Django 4.2.1 on 2024-03-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0048_alter_planta_lat_alter_planta_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='Qq',
            new_name='Cantidad',
        ),
        migrations.AddField(
            model_name='produccion',
            name='Id_Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produccion',
            name='Id_Lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote'),
        ),
    ]
