# Generated by Django 4.2.1 on 2024-03-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0049_rename_qq_produccion_cantidad_produccion_id_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='Id_Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.area'),
        ),
    ]
