# Generated by Django 4.2.1 on 2024-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0051_alter_produccion_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.FileField(upload_to='../../../../../../Uploads/Plantas/Fotos')),
            ],
        ),
    ]
