# Generated by Django 4.2.1 on 2024-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0055_alter_plantafoto_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='Coord_precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Coord_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Coord_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='Nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
