# Generated by Django 4.2.1 on 2024-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0056_lectura_coord_precision_lectura_coord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Coord_precision',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Coord_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Coord_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='Nombre',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
