# Generated by Django 4.2.1 on 2024-05-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0058_alter_area_nombre_alter_lectura_coord_precision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='Coord_precision',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Coord_x',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Coord_y',
        ),
    ]
