# Generated by Django 4.2.1 on 2024-05-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0059_remove_lectura_coord_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='Coord_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Coord_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Coord_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
