# Generated by Django 4.2.1 on 2024-06-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0060_lectura_coord_precision_lectura_coord_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='Variedad',
        ),
    ]
