# Generated by Django 4.2.1 on 2024-07-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0061_remove_lote_variedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=5)),
                ('Nombre', models.CharField(max_length=30)),
                ('MaximaCosechaHectareaAnual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MinimaCosechaHectareaAnual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
