# Generated by Django 4.2.1 on 2024-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0062_variedad_enfermedad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedad',
            name='MaximaCosechaHectareaAnual',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='MinimaCosechaHectareaAnual',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
