# Generated by Django 4.2.1 on 2024-07-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0063_alter_variedad_maximacosechahectareaanual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='Variedad',
        ),
        migrations.AddField(
            model_name='lote',
            name='Variedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.variedad'),
            preserve_default=False,
        ),
    ]
