# Generated by Django 4.2.1 on 2024-07-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0064_remove_area_variedad_lote_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='Variedad',
        ),
        migrations.AddField(
            model_name='area',
            name='Variedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.variedad'),
            preserve_default=False,
        ),
    ]
