# Generated by Django 4.2.1 on 2024-07-27 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0065_remove_lote_variedad_area_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocoordenadas',
            name='Id_Usuario',
        ),
        migrations.RemoveField(
            model_name='poligono',
            name='Id_Area',
        ),
        migrations.RemoveField(
            model_name='poligono',
            name='Id_Lote',
        ),
        migrations.RemoveField(
            model_name='poligono',
            name='Id_Usuario',
        ),
        migrations.AddField(
            model_name='area',
            name='Poligono',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.poligono'),
        ),
        migrations.AddField(
            model_name='lote',
            name='Poligono',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.poligono'),
        ),
    ]
