# Generated by Django 4.2.1 on 2024-07-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0067_remove_area_id_usuario_remove_lote_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Poligono',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='Poligono',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='GeoCoordenadas',
        ),
        migrations.DeleteModel(
            name='Poligono',
        ),
    ]
