# Generated by Django 4.2.1 on 2024-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0068_alter_area_poligono_alter_lote_poligono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Poligono',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='Poligono',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
