# Generated by Django 4.2.1 on 2024-03-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Clima",
            "0003_rename_crop_water_demand_daily_indicadores_atmospheric_pressure_max_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daily_indicadores",
            name="Sunshine_Duration",
        ),
    ]
