# Generated by Django 4.2.1 on 2024-03-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0005_rename_dew_temp_at_min_temp_daily_indicadores_dew_temp_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_indicadores',
            old_name='Precipitacion',
            new_name='Precipitation',
        ),
        migrations.RemoveField(
            model_name='daily_indicadores',
            name='Precipitacion_Hours',
        ),
    ]
