# Generated by Django 4.2.1 on 2024-03-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0006_rename_precipitacion_daily_indicadores_precipitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_indicadores',
            name='Device',
            field=models.CharField(null=True),
        ),
    ]
